export const TOP_50_CRYPTOS = [
  { symbol: 'SFM', name: 'SFM Token' },
  { symbol: 'BTC', name: 'Bitcoin' },
  { symbol: 'ETH', name: 'Ethereum' },
  { symbol: 'USDT', name: 'Tether' },
  { symbol: 'BNB', name: 'Binance Coin' },
  { symbol: 'XRP', name: 'Ripple' },
  { symbol: 'USDC', name: 'USD Coin' },
  { symbol: 'SOL', name: 'Solana' },
  { symbol: 'ADA', name: 'Cardano' },
  { symbol: 'AVAX', name: 'Avalanche' },
  { symbol: 'DOGE', name: 'Dogecoin' },
  { symbol: 'TRX', name: 'TRON' },
  { symbol: 'DOT', name: 'Polkadot' },
  { symbol: 'MATIC', name: 'Polygon' },
  { symbol: 'DAI', name: 'Dai' },
  { symbol: 'SHIB', name: 'Shiba Inu' },
  { symbol: 'LTC', name: 'Litecoin' },
  { symbol: 'UNI', name: 'Uniswap' },
  { symbol: 'LINK', name: 'Chainlink' },
  { symbol: 'ATOM', name: 'Cosmos' },
  { symbol: 'XLM', name: 'Stellar' },
  { symbol: 'BCH', name: 'Bitcoin Cash' },
  { symbol: 'XMR', name: 'Monero' },
  { symbol: 'ETC', name: 'Ethereum Classic' },
  { symbol: 'FIL', name: 'Filecoin' },
  { symbol: 'NEAR', name: 'NEAR Protocol' },
  { symbol: 'VET', name: 'VeChain' },
  { symbol: 'ALGO', name: 'Algorand' },
  { symbol: 'ICP', name: 'Internet Computer' },
  { symbol: 'HBAR', name: 'Hedera' },
  { symbol: 'MANA', name: 'Decentraland' },
  { symbol: 'SAND', name: 'The Sandbox' },
  { symbol: 'XTZ', name: 'Tezos' },
  { symbol: 'AAVE', name: 'Aave' },
  { symbol: 'EOS', name: 'EOS' },
  { symbol: 'CAKE', name: 'PancakeSwap' },
  { symbol: 'THETA', name: 'Theta Network' },
  { symbol: 'AXS', name: 'Axie Infinity' },
  { symbol: 'ZEC', name: 'Zcash' },
  { symbol: 'MKR', name: 'Maker' },
  { symbol: 'GRT', name: 'The Graph' },
  { symbol: 'FLOW', name: 'Flow' },
  { symbol: 'NEO', name: 'NEO' },
  { symbol: 'BAT', name: 'Basic Attention Token' },
  { symbol: 'CHZ', name: 'Chiliz' },
  { symbol: 'WAVES', name: 'Waves' },
  { symbol: 'ZIL', name: 'Zilliqa' },
  { symbol: 'ENJ', name: 'Enjin Coin' },
  { symbol: 'DASH', name: 'Dash' },
  { symbol: 'COMP', name: 'Compound' }
] as const;